; non-vanilla constants

MissileCooldown equ 9
SuperMissileCooldown equ 4
IceMissileCooldown equ 2
DiffusionMissileCooldown equ 1

MissileDamage equ 10
SuperMissileDamage equ 20
IceMissileDamage equ 10
DiffusionMissileDamage equ 5

CustomMessages_Maximum equ 199 ; 57 Messages are reserved by existing behavior, leaving 199 ids left

ScrewAttackWJFlag equ 3000001h ; Flag that is set when WallJumping with Screw Attack