name: Makefile CI

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        config:
          - mode: randomizer
            zip-name: Randomizer Patches
          - mode: nonlinear
            zip-name: Nonlinear patches
            
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Copy game file
      run: cp --no-preserve=mode $METROID_FUSION_U_PATH ./metroid4.gba

    - name: Run make
      run: make dist AS=armips FLIPS=flips BUILD_TYPE=release MODIFICATION_MODE=${{ matrix.config.mode }}

    - name: Remove ROM
      run: rm ./bin/m4rs.gba

    - name: Upload patches as artifacts
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4.0.0
      with:
        name: ${{ matrix.config.zip-name }}.zip
        if-no-files-found: error
        path: |
          ./bin/*.ips
          ./bin/*.bps

  release:
    runs-on: 'ubuntu-latest'
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs:
      - build
    permissions: write-all

    steps:
      - name: Download all the artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: "*.zip"
          path: artifacts/

      - name: Create a Draft Release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/*
          file_glob: true
          tag: ${{ github.ref }}
          draft: true
          body: "Insert Changelog here"
        

      
